@url = http://localhost:8080/v1
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTU0NjEyMjcsInN1YiI6MX0.XMN-OZ6hxdRmiTrDwHYcT_4CyHgSmaH9neMZEmOCZvo
### AUTH
# REGISTER
POST {{url}}/staff/register
Content-Type: application/json

{
	"phoneNumber": "+628123123123",
	"name": "budi satu",
	"password": "test1234"
}
###
#LOGIN
POST {{url}}/staff/login
Content-Type: application/json

{
	"phoneNumber": "+628123123123",
	"password": "test1234"
}
### PRODUCT
#GETALL
GET {{url}}/product?limit=10&offset=0&name=3&isAvailable=true&category=Clothing&price=desc&createdAt=desc&inStock=true
###
#CREATE
POST {{url}}/product
Content-Type: application/json
Authorization: {{token}}

{
	"name": "1123",
	"sku": "TS123",
	"category": "Beverages",
	"imageUrl": "http://test.net.aaa/123",
	"notes": "Comfortable cotton material, available in various sizes and colors.",
	"price": 15,
	"stock": 50,
	"location": "Store A",
	"isAvailable": true
}
###
#GETBYID
GET {{url}}/product/30
###
#UPDATE
PUT {{url}}/product/1
Content-Type: application/json

{
	"name": "11234",
	"sku": "TS123",
	"category": "Beverages",
	"imageUrl": "https://example.com/image.jpg",
	"notes": "Comfortable cotton material, available in various sizes and colors.",
	"price": 15,
	"stock": 50,
	"location": "Store A",
	"isAvailable": true
}
###
#DELETE
DELETE {{url}}/product/2