@url = http://localhost:8080/v1
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTUzODc0MTQsInN1YiI6MX0.E4a1xzCtWC-N8NfdF3yeWrTpp1CrMLCYLZBWa_ZInHw
### AUTH
# REGISTER
POST {{url}}/staff/register
Content-Type: application/json

{
	"phoneNumber": "+628123123123",
	"name": "budi satu",
	"password": "test1234"
}
###
#LOGIN
POST {{url}}/staff/login
Content-Type: application/json

{
	"phoneNumber": "+628123123123",
	"password": "test1234"
}
### PRODUCT
#CREATE
POST {{url}}/product/create
Content-Type: application/json

{
	"name": "1123",
	"sku": "TS123",
	"category": "Beverages",
	"imageUrl": "https://example.com/image.jpg",
	"notes": "Comfortable cotton material, available in various sizes and colors.",
	"price": 15,
	"stock": 50,
	"location": "Store A",
	"isAvailable": true
}
